# **Students' Marks Prediction and Improvement**

## Import Dependencies

In [ ]:
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import joblib

## Setting up Directories and Environments

In [ ]:
list_of_data_path = os.listdir('dataset')
list_of_data_path = ['dataset/' + i for i in list_of_data_path]

sub_name_list = []
classification_report_dict = {
    'svm_nfp' : {},
    'svm_ros' : {},
    'svm_rus' : {},
    'xgb_nfp' : {},
    'xgb_ros' : {},
    'xgb_rus' : {}
}
temp_dict = {}

## SVM Classifier

### With No Further Processing

In [ ]:
for i in range(len(list_of_data_path)):
  data = pd.read_excel(list_of_data_path[i], index_col=0)
  data.replace(-1, 0, inplace = True)
  sub_name = list_of_data_path[i].split('/')[3].split('_')[1].split('.')[0]
  sub_name_list.append(sub_name)

  passes = pd.Series(data['ese'] >= 40)
  data = pd.concat([data, passes.rename("Result")], axis=1)

  data.replace({'Result' : {True : 1, False : 0}}, inplace = True)

  X = data[['att','ct1','ct2','ta']]
  y = data['Result']
  X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3 , random_state = 2529)

  model = LogisticRegression()
  model.fit(X_train, y_train)
  y_pred  = model.predict(X_test)

  temp_dict = classification_report(y_test, y_pred, output_dict=True)
  classification_report_dict['svm_nfp'][sub_name + '_model'] = round(temp_dict['accuracy'] * 100, 2)

  print(str(i+1) + '. ' + sub_name)
  print('\nConfusion Matrix :\n')
  print(confusion_matrix(y_test, y_pred))
  print('\n\nClassification Report :\n')
  print(classification_report(y_test, y_pred))
  print('-' * 55)
  print('\n')

1. ccwt

Confusion Matrix :

[[ 5  3]
 [ 4 21]]


Classification Report :

              precision    recall  f1-score   support

           0       0.56      0.62      0.59         8
           1       0.88      0.84      0.86        25

    accuracy                           0.79        33
   macro avg       0.72      0.73      0.72        33
weighted avg       0.80      0.79      0.79        33

-------------------------------------------------------


2. mca

Confusion Matrix :

[[ 1  8]
 [ 4 19]]


Classification Report :

              precision    recall  f1-score   support

           0       0.20      0.11      0.14         9
           1       0.70      0.83      0.76        23

    accuracy                           0.62        32
   macro avg       0.45      0.47      0.45        32
weighted avg       0.56      0.62      0.59        32

-------------------------------------------------------


3. java

Confusion Matrix :

[[ 4  7]
 [ 2 20]]


Classification Report :

      

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

13. iwt

Confusion Matrix :

[[ 0  7]
 [ 0 23]]


Classification Report :

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         7
           1       0.77      1.00      0.87        23

    accuracy                           0.77        30
   macro avg       0.38      0.50      0.43        30
weighted avg       0.59      0.77      0.67        30

-------------------------------------------------------


14. sepm

Confusion Matrix :

[[ 6  4]
 [ 1 22]]


Classification Report :

              precision    recall  f1-score   support

           0       0.86      0.60      0.71        10
           1       0.85      0.96      0.90        23

    accuracy                           0.85        33
   macro avg       0.85      0.78      0.80        33
weighted avg       0.85      0.85      0.84        33

-------------------------------------------------------


15. imt

Confusion Matrix :

[[ 0  7]
 [ 0 23]]


Classification Report :

    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

16. dwt

Confusion Matrix :

[[6 9]
 [7 8]]


Classification Report :

              precision    recall  f1-score   support

           0       0.46      0.40      0.43        15
           1       0.47      0.53      0.50        15

    accuracy                           0.47        30
   macro avg       0.47      0.47      0.46        30
weighted avg       0.47      0.47      0.46        30

-------------------------------------------------------


17. cc

Confusion Matrix :

[[ 4  8]
 [ 1 19]]


Classification Report :

              precision    recall  f1-score   support

           0       0.80      0.33      0.47        12
           1       0.70      0.95      0.81        20

    accuracy                           0.72        32
   macro avg       0.75      0.64      0.64        32
weighted avg       0.74      0.72      0.68        32

-------------------------------------------------------


18. cg

Confusion Matrix :

[[ 9 11]
 [ 2 11]]


Classification Report :

           

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

25. ada

Confusion Matrix :

[[11  4]
 [ 5 13]]


Classification Report :

              precision    recall  f1-score   support

           0       0.69      0.73      0.71        15
           1       0.76      0.72      0.74        18

    accuracy                           0.73        33
   macro avg       0.73      0.73      0.73        33
weighted avg       0.73      0.73      0.73        33

-------------------------------------------------------


26. mp

Confusion Matrix :

[[14  5]
 [ 2 12]]


Classification Report :

              precision    recall  f1-score   support

           0       0.88      0.74      0.80        19
           1       0.71      0.86      0.77        14

    accuracy                           0.79        33
   macro avg       0.79      0.80      0.79        33
weighted avg       0.80      0.79      0.79        33

-------------------------------------------------------




### With Random OverSampling

In [ ]:
for i in range(len(list_of_data_path)):
  data = pd.read_excel(list_of_data_path[i], index_col=0)
  data.replace(-1, 0, inplace = True)
  sub_name = list_of_data_path[i].split('/')[3].split('_')[1].split('.')[0]

  passes = pd.Series(data['ese'] >= 40)
  data = pd.concat([data, passes.rename("Result")], axis=1)

  data.replace({'Result' : {True : 1, False : 0}}, inplace = True)

  X = data[['att','ct1','ct2','ta']]
  y = data['Result']
  ros = RandomOverSampler(random_state = 12529)
  X_ros, y_ros = ros.fit_resample(X, y)

  X_train, X_test, y_train, y_test = train_test_split(X_ros, y_ros, test_size = 0.3 , random_state = 2529)

  model = LogisticRegression()
  model.fit(X_train, y_train)
  y_pred  = model.predict(X_test)

  temp_dict = classification_report(y_test, y_pred, output_dict=True)
  classification_report_dict['svm_ros'][sub_name + '_model'] = round(temp_dict['accuracy'] * 100, 2)

  print(str(i+1) + '. ' + sub_name)
  print('\nConfusion Matrix :\n')
  print(confusion_matrix(y_test, y_pred))
  print('\n\nClassification Report :\n')
  print(classification_report(y_test, y_pred))
  print('-' * 55)
  print('\n')

1. ccwt

Confusion Matrix :

[[12 11]
 [ 5 17]]


Classification Report :

              precision    recall  f1-score   support

           0       0.71      0.52      0.60        23
           1       0.61      0.77      0.68        22

    accuracy                           0.64        45
   macro avg       0.66      0.65      0.64        45
weighted avg       0.66      0.64      0.64        45

-------------------------------------------------------


2. mca

Confusion Matrix :

[[11  7]
 [ 8 13]]


Classification Report :

              precision    recall  f1-score   support

           0       0.58      0.61      0.59        18
           1       0.65      0.62      0.63        21

    accuracy                           0.62        39
   macro avg       0.61      0.62      0.61        39
weighted avg       0.62      0.62      0.62        39

-------------------------------------------------------


3. java

Confusion Matrix :

[[15  7]
 [ 2 19]]


Classification Report :

      

### With Random UnderSampling

In [ ]:
for i in range(len(list_of_data_path)):
  data = pd.read_excel(list_of_data_path[i], index_col=0)
  data.replace(-1, 0, inplace = True)
  sub_name = list_of_data_path[i].split('/')[3].split('_')[1].split('.')[0]

  passes = pd.Series(data['ese'] >= 40)
  data = pd.concat([data, passes.rename("Result")], axis=1)

  data.replace({'Result' : {True : 1, False : 0}}, inplace = True)

  X = data[['att','ct1','ct2','ta']]
  y = data['Result']
  rus = RandomUnderSampler(random_state = 12529)
  X_rus, y_rus = rus.fit_resample(X, y)

  X_train, X_test, y_train, y_test = train_test_split(X_rus, y_rus, test_size = 0.3 , random_state = 2529)

  model = LogisticRegression()
  model.fit(X_train, y_train)
  y_pred  = model.predict(X_test)

  temp_dict = classification_report(y_test, y_pred, output_dict=True)
  classification_report_dict['svm_rus'][sub_name + '_model'] = round(temp_dict['accuracy'] * 100, 2)

  print(str(i+1) + '. ' + sub_name)
  print('\nConfusion Matrix :\n')
  print(confusion_matrix(y_test, y_pred))
  print('\n\nClassification Report :\n')
  print(classification_report(y_test, y_pred))
  print('-' * 55)
  print('\n')

1. ccwt

Confusion Matrix :

[[ 4  3]
 [ 3 10]]


Classification Report :

              precision    recall  f1-score   support

           0       0.57      0.57      0.57         7
           1       0.77      0.77      0.77        13

    accuracy                           0.70        20
   macro avg       0.67      0.67      0.67        20
weighted avg       0.70      0.70      0.70        20

-------------------------------------------------------


2. mca

Confusion Matrix :

[[6 4]
 [6 8]]


Classification Report :

              precision    recall  f1-score   support

           0       0.50      0.60      0.55        10
           1       0.67      0.57      0.62        14

    accuracy                           0.58        24
   macro avg       0.58      0.59      0.58        24
weighted avg       0.60      0.58      0.59        24

-------------------------------------------------------


3. java

Confusion Matrix :

[[7 4]
 [3 8]]


Classification Report :

              

## XGB Classifier

### With No Further Processing

In [ ]:
for i in range(len(list_of_data_path)):
  data = pd.read_excel(list_of_data_path[i], index_col=0)
  data.replace(-1, 0, inplace = True)
  sub_name = list_of_data_path[i].split('/')[3].split('_')[1].split('.')[0]

  passes = pd.Series(data['ese'] >= 40)
  data = pd.concat([data, passes.rename("Result")], axis=1)

  data.replace({'Result' : {True : 1, False : 0}}, inplace = True)

  X = data[['att','ct1','ct2','ta']]
  y = data['Result']
  X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3 , random_state = 2529)

  model = xgb.XGBClassifier()
  model.fit(X_train, y_train)
  y_pred  = model.predict(X_test)

  temp_dict = classification_report(y_test, y_pred, output_dict=True)
  classification_report_dict['xgb_nfp'][sub_name + '_model'] = round(temp_dict['accuracy'] * 100, 2)

  print(str(i+1) + '. ' + sub_name)
  print('\nConfusion Matrix :\n')
  print(confusion_matrix(y_test, y_pred))
  print('\n\nClassification Report :\n')
  print(classification_report(y_test, y_pred))
  print('-' * 55)
  print('\n')

1. ccwt

Confusion Matrix :

[[ 5  3]
 [ 4 21]]


Classification Report :

              precision    recall  f1-score   support

           0       0.56      0.62      0.59         8
           1       0.88      0.84      0.86        25

    accuracy                           0.79        33
   macro avg       0.72      0.73      0.72        33
weighted avg       0.80      0.79      0.79        33

-------------------------------------------------------


2. mca

Confusion Matrix :

[[ 5  4]
 [ 3 20]]


Classification Report :

              precision    recall  f1-score   support

           0       0.62      0.56      0.59         9
           1       0.83      0.87      0.85        23

    accuracy                           0.78        32
   macro avg       0.73      0.71      0.72        32
weighted avg       0.77      0.78      0.78        32

-------------------------------------------------------


3. java

Confusion Matrix :

[[ 5  6]
 [ 2 20]]


Classification Report :

      

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

17. cc

Confusion Matrix :

[[ 3  9]
 [ 8 12]]


Classification Report :

              precision    recall  f1-score   support

           0       0.27      0.25      0.26        12
           1       0.57      0.60      0.59        20

    accuracy                           0.47        32
   macro avg       0.42      0.42      0.42        32
weighted avg       0.46      0.47      0.46        32

-------------------------------------------------------


18. cg

Confusion Matrix :

[[12  8]
 [ 4  9]]


Classification Report :

              precision    recall  f1-score   support

           0       0.75      0.60      0.67        20
           1       0.53      0.69      0.60        13

    accuracy                           0.64        33
   macro avg       0.64      0.65      0.63        33
weighted avg       0.66      0.64      0.64        33

-------------------------------------------------------


19. m3

Confusion Matrix :

[[ 9  7]
 [ 4 13]]


Classification Report :

        

### With Random OverSampling

In [ ]:
for i in range(len(list_of_data_path)):
  data = pd.read_excel(list_of_data_path[i], index_col=0)
  data.replace(-1, 0, inplace = True)
  sub_name = list_of_data_path[i].split('/')[3].split('_')[1].split('.')[0]

  passes = pd.Series(data['ese'] >= 40)
  data = pd.concat([data, passes.rename("Result")], axis=1)

  data.replace({'Result' : {True : 1, False : 0}}, inplace = True)

  X = data[['att','ct1','ct2','ta']]
  y = data['Result']
  ros = RandomOverSampler(random_state = 12529)
  X_ros, y_ros = ros.fit_resample(X, y)

  X_train, X_test, y_train, y_test = train_test_split(X_ros, y_ros, test_size = 0.3 , random_state = 2529)

  model = xgb.XGBClassifier()
  model.fit(X_train, y_train)

  joblib.dump(model, '/content/models/' + sub_name + '_model.pkl')

  y_pred  = model.predict(X_test)

  temp_dict = classification_report(y_test, y_pred, output_dict=True)
  classification_report_dict['xgb_ros'][sub_name + '_model'] = round(temp_dict['accuracy'] * 100, 2)

  print(str(i+1) + '. ' + sub_name)
  print('\nConfusion Matrix :\n')
  print(confusion_matrix(y_test, y_pred))
  print('\n\nClassification Report :\n')
  print(classification_report(y_test, y_pred))
  print('-' * 55)
  print('\n')

1. ccwt

Confusion Matrix :

[[19  4]
 [ 6 16]]


Classification Report :

              precision    recall  f1-score   support

           0       0.76      0.83      0.79        23
           1       0.80      0.73      0.76        22

    accuracy                           0.78        45
   macro avg       0.78      0.78      0.78        45
weighted avg       0.78      0.78      0.78        45

-------------------------------------------------------


2. mca

Confusion Matrix :

[[13  5]
 [ 4 17]]


Classification Report :

              precision    recall  f1-score   support

           0       0.76      0.72      0.74        18
           1       0.77      0.81      0.79        21

    accuracy                           0.77        39
   macro avg       0.77      0.77      0.77        39
weighted avg       0.77      0.77      0.77        39

-------------------------------------------------------


3. java

Confusion Matrix :

[[17  5]
 [ 4 17]]


Classification Report :

      

### With Random UnderSampling

In [ ]:
for i in range(len(list_of_data_path)):
  data = pd.read_excel(list_of_data_path[i], index_col=0)
  data.replace(-1, 0, inplace = True)
  sub_name = list_of_data_path[i].split('/')[3].split('_')[1].split('.')[0]

  passes = pd.Series(data['ese'] >= 40)
  data = pd.concat([data, passes.rename("Result")], axis=1)

  data.replace({'Result' : {True : 1, False : 0}}, inplace = True)

  X = data[['att','ct1','ct2','ta']]
  y = data['Result']
  rus = RandomUnderSampler(random_state = 12529)
  X_rus, y_rus = rus.fit_resample(X, y)

  X_train, X_test, y_train, y_test = train_test_split(X_rus, y_rus, test_size = 0.3 , random_state = 2529)

  model = xgb.XGBClassifier()
  model.fit(X_train, y_train)
  y_pred  = model.predict(X_test)

  temp_dict = classification_report(y_test, y_pred, output_dict=True)
  classification_report_dict['xgb_rus'][sub_name + '_model'] = round(temp_dict['accuracy'] * 100, 2)

  print(str(i+1) + '. ' + sub_name)
  print('\nConfusion Matrix :\n')
  print(confusion_matrix(y_test, y_pred))
  print('\n\nClassification Report :\n')
  print(classification_report(y_test, y_pred))
  print('-' * 55)
  print('\n')

1. ccwt

Confusion Matrix :

[[ 4  3]
 [ 3 10]]


Classification Report :

              precision    recall  f1-score   support

           0       0.57      0.57      0.57         7
           1       0.77      0.77      0.77        13

    accuracy                           0.70        20
   macro avg       0.67      0.67      0.67        20
weighted avg       0.70      0.70      0.70        20

-------------------------------------------------------


2. mca

Confusion Matrix :

[[ 4  6]
 [ 3 11]]


Classification Report :

              precision    recall  f1-score   support

           0       0.57      0.40      0.47        10
           1       0.65      0.79      0.71        14

    accuracy                           0.62        24
   macro avg       0.61      0.59      0.59        24
weighted avg       0.62      0.62      0.61        24

-------------------------------------------------------


3. java

Confusion Matrix :

[[ 5  6]
 [ 1 10]]


Classification Report :

      

## Model Mecric Report

In [ ]:
model_metrics = pd.DataFrame(classification_report_dict)
model_metrics.loc['average'] = model_metrics.mean(axis = 0)
model_metrics['average'] = model_metrics.mean(axis = 1)
model_metrics.round(2)

svm_nfp  svm_ros  svm_rus  xgb_nfp  xgb_ros  xgb_rus  average
ccwt_model    78.79    64.44    70.00    78.79    77.78    70.00    73.30
mca_model     62.50    61.54    58.33    78.12    76.92    62.50    66.65
java_model    72.73    79.07    68.18    75.76    79.07    68.18    73.83
ai_model      66.67    43.59    47.62    46.67    66.67    38.10    51.55
pslb_model    63.64    52.63    66.67    66.67    60.53    62.96    62.18
np_model      84.38    66.67    73.33    84.38    89.58    80.00    79.72
dsa_model     60.61    65.85    62.50    60.61    70.73    66.67    64.50
os_model      72.73    76.19    65.22    63.64    76.19    47.83    66.97
cs_model      72.73    65.12    60.87    84.85    69.77    69.57    70.48
deld_model    78.79    79.25    69.23    72.73    92.45    76.92    78.23
cn_model      72.73    57.14    56.52    75.76    66.67    56.52    64.22
cm_model      66.67    62.22    61.90    57.58    68.89    47.62    60.81
iwt_model     76.67    29.17    33.33    66.67    64.58    41.67    52.02
sepm_model    84.85    67.39    52.63    84.85    78.26    52.63    70.10
imt_model     76.67    75.51    18.18    76.67    75.51    18.18    56.79
dwt_model     46.67    63.64    59.26    66.67    57.58    59.26    58.85
cc_model      71.88    58.97    45.83    46.88    58.97    41.67    54.03
cg_model      60.61    72.73    59.38    63.64    60.61    40.62    59.60
m3_model      69.70    75.76    71.88    66.67    75.76    53.12    68.82
crp_model     68.75    55.81    66.67    68.75    62.79    57.14    63.32
csa_model     66.67    66.67    62.07    63.64    69.44    58.62    64.52
be_model      63.64    65.79    66.67    75.76    71.05    77.78    70.12
ppc_model     65.62    77.27    50.00    78.12    77.27    60.00    68.05
dms_model     57.58    67.50    60.00    69.70    65.00    48.00    61.30
ada_model     72.73    60.61    59.38    63.64    48.48    68.75    62.27
mp_model      78.79    75.00    79.31    75.76    72.22    62.07    73.86
average       69.76    64.83    59.42    69.73    70.49    57.17    65.23

## Sample Prediction

### Function to predict result

In [ ]:
def predict_my_result(sub_name, att, ct1, ct2, ta):
  model_name = '/content/models/' + sub_name + '_model.pkl'
  model = joblib.load(model_name)
  test_row = pd.DataFrame([[att, ct1, ct2, ta]], columns = ['att', 'ct1', 'ct2', 'ta'])
  return model.predict(test_row)[0]

### Predict My Result

In [ ]:
print('Subject keys : ')
print('cn', 'cm', 'be','dsa','cs','pslb','imt','mca','dms','java','cg','m3','ai','\niwt','np','dwt','cc','ccwt','os','sepm','ada','mp','deld','crp','csa','ppc')
sub_name = input('Enter the subject name : ')
att = int(input('Enter the attendence : '))
ct1 = int(input('Enter the marks obtained in ct 1 : '))
ct2 = int(input('Enter the marks obtained in ct 2 : '))
ta = int(input('Enter the marks obtained in ta : '))

result = predict_my_result(sub_name, att, ct1, ct2, ta)

if result == 1:
  print("Congratulations, you may pass")
else:
  print("Commiserations, you need to work harder")

Subject keys : 
cn cm be dsa cs pslb imt mca dms java cg m3 ai 
iwt np dwt cc ccwt os sepm ada mp deld crp csa ppc
Enter the subject name : dsa
Enter the attendence : 60
Enter the marks obtained in ct 1 : 30
Enter the marks obtained in ct 2 : 40
Enter the marks obtained in ta : 12
Commiseration, you need to work harder


# **End of File**